local colors = require("seoul256/colors")

return {
  -- BlinkCmpMenu = colors.none_, -- Default: Pmenu	The completion menu window
  -- BlinkCmpMenuBorder = colors.none_, -- Default: Pmenu	The completion menu window border
  -- BlinkCmpMenuSelection = colors.none_, -- Default: PmenuSel	The completion menu window selected item
  -- BlinkCmpScrollBarThumb = colors.none_, -- Default: PmenuThumb	The scrollbar thumb
  -- BlinkCmpScrollBarGutter = colors.none_, -- Default: PmenuSbar	The scrollbar gutter
  -- BlinkCmpLabel = colors.none_, -- Default: Pmenu	Label of the completion item
  -- BlinkCmpLabelDeprecated = colors.none_, -- Default: PmenuExtra	Deprecated label of the completion item
  -- BlinkCmpLabelMatch = colors.none_, -- Default: Pmenu	(Currently unused) Label of the completion item when it matches the query
  -- BlinkCmpLabelDetail = colors.none_, -- Default: PmenuExtra	Label description of the completion item
  -- BlinkCmpLabelDescription = colors.none_, -- Default: PmenuExtra	Label description of the completion item
  -- BlinkCmpKind = colors.none_, -- Default: PmenuKind	Kind icon/text of the completion item
  BlinkCmpKindText = colors.string_,
  BlinkCmpKindMethod = colors.method,
  BlinkCmpKindFunction = colors.function_,
  BlinkCmpKindConstructor = colors.constructor,
  BlinkCmpKindField = colors.member,
  BlinkCmpKindVariable = colors.variable,
  BlinkCmpKindClass = colors.class,
  BlinkCmpKindInterface = colors.class,
  BlinkCmpKindModule = colors.module,
  BlinkCmpKindProperty = colors.property_,
  BlinkCmpKindUnit = colors.builtin,
  BlinkCmpKindValue = colors.dark_fg,
  BlinkCmpKindEnum = colors.enum,
  BlinkCmpKindKeyword = colors.keyword,
  BlinkCmpKindSnippet = colors.green,
  BlinkCmpKindColor = colors.bright_yellow,
  BlinkCmpKindFile = colors.yellow,
  BlinkCmpKindReference = colors.none_,
  BlinkCmpKindFolder = colors.blue,
  BlinkCmpKindEnumMember = colors.enum,
  BlinkCmpKindConstant = colors.constant,
  BlinkCmpKindStruct = colors.structure,
  BlinkCmpKindEvent = colors.red,
  BlinkCmpKindOperator = colors.operator,
  BlinkCmpKindTypeParameter = colors.type,
  -- BlinkCmpSource = colors.none_, -- Default: PmenuExtra	Source of the completion item
  -- BlinkCmpGhostText = colors.none_, -- Default: NonText	Preview item with ghost text
  -- BlinkCmpDoc = colors.none_, -- Default: NormalFloat	The documentation window
  -- BlinkCmpDocBorder = colors.none_, -- Default: NormalFloat	The documentation window border
  -- BlinkCmpDocSeparator = colors.none_, -- Default: NormalFloat	The documentation separator between doc and detail
  -- BlinkCmpDocCursorLine = colors.none_, -- Default: Visual	The documentation window cursor line
  -- BlinkCmpSignatureHelp = colors.none_, -- Default: NormalFloat	The signature help window
  -- BlinkCmpSignatureHelpBorder = colors.none_, -- Default: NormalFloat	The signature help window border
  -- BlinkCmpSignatureHelpActiveParameter = colors.none_, -- Default: LspSignatureActiveParameter	Active parameter of the signature help
}
