colors = require("seoul256.colors")

return {
  TodoDone = colors.comment,
  TodoPriorityA = colors.bright_red,
  TodoPriorityB = colors.red,
  TodoPriorityC = colors.bright_yellow,
  TodoPriorityD = colors.yellow,
  TodoPriorityE = colors.bright_green,
  TodoPriorityG = colors.white,
  TodoPriorityH = colors.white,
  TodoPriorityI = colors.white,
  TodoPriorityJ = colors.white,
  TodoPriorityK = colors.white,
  TodoPriorityL = colors.white,
  TodoPriorityM = colors.white,
  TodoPriorityN = colors.white,
  TodoPriorityO = colors.white,
  TodoPriorityP = colors.white,
  TodoPriorityQ = colors.white,
  TodoPriorityR = colors.white,
  TodoPriorityS = colors.white,
  TodoPriorityT = colors.white,
  TodoPriorityU = colors.white,
  TodoPriorityV = colors.white,
  TodoPriorityW = colors.white,
  TodoPriorityX = colors.white,
  TodoPriorityY = colors.white,
  TodoPriorityZ = colors.white,
  TodoDate = colors.bright_black,
  TodoProject = colors.special,
  TodoContext = colors.string_,
}
